version: '3.8'
services:
  db:
    image: postgres:15.3
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: assignment_1_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  web:
    build: .
    environment:
          - SERVE_STATIC_ASSETS=${SERVE_STATIC_ASSETS:-true}
          - CUSTOM_STORAGE_PATH=/myapp/custom_storage
          - REDIS_URL=redis://redis:6379/0
          - DB_HOST=db
          - ELASTICSEARCH_URL=http://elasticsearch:9200
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
  varnish:
    image: varnish:7.3
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    environment:
      - VARNISH_SIZE=256M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  db_data:
  esdata: